name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.11
  image_picker: ^1.0.0  # or the latest version
  path: ^1.8.0
  mime: ^1.0.4

  
  go_router: ^13.0.1  # Use the latest version available3

  english_words: ^4.0.0
  provider: ^6.1.5
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/MAX.png
    - assets/images/Bella.png
    - assets/images/bullterrier.png
    - assets/images/Cosma.png
    - assets/images/brutus.png
    - assets/images/placeholder.png
    - assets/images/process_icon.png
    - assets/images/main_page.png
    - assets/images/teamphoto.png
    - assets/images/gallery2.png
    - assets/images/gallery1.png
    - assets/images/gallery3.png
    - assets/images/dog-adoption-form.png


